<?php

$idiom = array(
		'Individual registration form',
		'fill in one form per person',
		'Contact details',
		'(runners, managers, trainers...)',
		'I am the runner and I register myself:',
		'I am the representative (manager, trainer...), Get in touch with me',
		'Name *',
		'Surname *',
		'Email *',
		'Cel. phone',
		'* compulsory information',
		'Choose the race you want to take part in *',
		'race',
		'qualifying standard',
		'series',
		'Runner`s details',
		'Club, Locality, School ',
		'Licence No. ',
		'Birth year *',
		'Sex',
		'Male',
		'Female',
		'More details *',
		'Best valid record 2015 *',
		'Best valid record 2014 *',
		'Personal best valid record *',
		'If you want to give other details to help organization, please use this box.',
		'Finish your registration',
		'I read and accept the <a href="2012 Confidencialidad de Datos.pdf">legal conditions</a> and <a href="reglamento mt2016.pdf">rules</a>',
		'send',
		'reset',
		'International Meeting Villa de Bilbao',
		'Your enrolment application has arrived successfully, in a few days you will get an email from Club Atletismo Santutxu to confirm the acceptance of your participation.'."\n\n".'Thanks for your intererst.'."\n\n".'Club Atletismo Santutxu',
		'(All marks with comma example: 24,50/ 7,55)',
		'Benjamin and Alevin (2005/2008)',
		'Infant and Cadet (2002/2004)',
        'Pole',
        'Discipline can not be left empty',
        'In personal records should not appear points, use commas only',
		'Invalid birthday year',
		'The birthday year doesn´t match with the selected discipline'
);
?>