<?php

$idiom = array(
		'Banakako inskripzioak egiteko txostena',
		'korrikalari bakoitseko txosten bat bete behar da',
		'Kontaktuan jartzeko datuak',
		'(korrikalaria, manager, entrenatzailea...)',
		'Korrikalaria naiz, eta nire izenean egiten dut inskripzioa:',
		'Korrikalariaren Ordezkaria naiz (Manager, Entrenatzailea...). Nirekin kontaktuan jarri',
		'Izena *',
		'Abizenak *',
		'Helbide elektronikoa *',
		'Mugikorra',
		'* derrigorrezko eremuak',
		'Parte hartu nahi den frogak aukeratu *',
		'froga',
		'gutxieneko marka',
		'series',
		'Korrikalariaren datuak',
		'Kluba ',
		'Lizentzia Zb. ',
		'Jaiotze Urtea *',
		'Sexo',
		'Masculino',
		'Femenino',
		'Datu gehiago *',
		'2015ko baliozko markarik onena *',
		'2014ko baliozko markarik onena *',
		'Baliozko markarik onena *',
		'ANTOLATZAILEEI LANA ERRAZTEKO datu gehiago gehitzea beharrezkoa baldin bada, eremu hau erebili..',
		'Inskripzioa amaitu',
		'<a href="2012 Confidencialidad de Datos.pdf">Lege-baldintzak</a> eta <a href="reglamento mt2016.pdf">araudia</a> irakurri eta onartzen ditut',
		'datuak bidali',
		'dena ezabatu',
		'Reunión Internacional Villa de Bilbao',
		'Zure izen emate eskaria behar bezala jaso da. Datozen egunetan Santutxu Atletismo Taldearen mezu bat jasoko duzu, zure partaidetza onartzeko.'."\n\n".'Eskerrik asko zure interesarengatik.'."\n\n".'Santutxu Atletismo Taldea.',
		'(Komekin marka guztiak. Adibidez: 24,50 / 7,55)',
		'Haurra eta Alebin (2005/2008)',
		'Haur eta kadete (2002/2004)',
        'Pole',
        'Proba ezin da hutsik egon',
        'Erregistro pertsonalak behar ez dirudi puntu, koma soilik erabili',
		'Jaiotza-urtea baliogabea',
		'Jaiotze-data ez dator bat aukeratutako test'
);
?>