version: '3'

services:

  web:
    image: jtoirac/nginx-mainline-alpine:1.0
    container_name: ports
    user: root
    environment:
      VIRTUAL_HOST: concentrador.server
    ports:
      - 80:80
    volumes:
      - ./sites-74:/var/www/html
      - ./app/web/conf/concentrador-app.conf:/etc/nginx/conf.d/default.conf
      - ./app/web/conf/custom_404.html:/usr/share/nginx/html/custom_404.html
      - ./app/web/conf/custom_50x.html:/usr/share/nginx/html/custom_50x.html
      - ./logs:/var/log/nginx
    restart: always
    depends_on:
      - php7.4

  php7.4:
    image: jtoirac/php7.4:1.0
    container_name: php
    user: root
    volumes:
      - ./sites-74:/var/www/html
      - ./app/php/php.ini:/usr/local/etc/php/php.ini
      - ./app/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: jtoirac/mariadb_lt:1.0
    user: root
    ports:
      - 3307:3306
    volumes:
      - ./config/server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./logs:/var/log/mysql
      - mysql:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    restart: always

volumes:
  mysql:

