version: '3'

services:

  web:
    image: jtoirac/nginx-mainline-alpine:1.0
    container_name: web
    user: root
    environment:
      VIRTUAL_HOST: concentrador.server
    expose:
      - 80
    volumes:
      - ./sites-56:/var/www/html
      - ./app/web/conf/concentrador-app.conf:/etc/nginx/conf.d/default.conf
      - ./app/web/conf/custom_404.html:/usr/share/nginx/html/custom_404.html
      - ./app/web/conf/custom_50x.html:/usr/share/nginx/html/custom_50x.html
      - ./logs:/var/log/nginx
    restart: always
    depends_on:
      - php5.6

  php5.6:
    image: jtoirac/php5.6:1.0
    container_name: php
    user: root
    volumes:
      - ./sites-56:/var/www/html
      - ./app/php/php.ini:/usr/local/etc/php/php.ini
      - ./app/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: jtoirac/mariadb_lt:1.0
    user: root
    ports:
      - 3307:3306
    volumes:
      - ./config/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./logs:/var/log/mysql
      - mysql:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  phpmyadmin:
    image: 192.168.0.6:8083/phpmyadmin/phpmyadmin:v20210531
    user: root
    container_name: phpmyadmin
    expose:
      - 80
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=http://pma.server/
      - UPLOAD_LIMIT=300M
    restart: always
    depends_on:
      - mariadb

volumes:
  mysql:

