DROP VIEW IF EXISTS `bitacora`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `bitacora` AS select `a`.`login` AS `login`,`b`.`texto` AS `texto`,from_unixtime(`b`.`fecha`) AS `fecha`,`a`.`idrol` AS `idrol`,(case `a`.`idcomercio` when _utf8'todos' then _utf8'todos' else (select `tbl_comercio`.`nombre` AS `nombre` from `tbl_comercio` where (`tbl_comercio`.`idcomercio` = `a`.`idcomercio`)) end) AS `comercio` from (`tbl_baticora` `b` join `tbl_admin` `a`) where ((`a`.`idadmin` = `b`.`idadmin`) and (`a`.`idrol` > 10) and (`a`.`login` like _utf8'%')) order by `a`.`login`,`b`.`fecha` desc;
	
DROP VIEW IF EXISTS `listadoIp`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `listadoIp` AS select `tbl_listaIp`.`ip` AS `ip`,date_format(from_unixtime(`tbl_listaIp`.`fecha`),_utf8'%d/%m/%Y %H:%i') AS `fecha`,`tbl_listaIp`.`fecha` AS `fechatruc` from `tbl_listaIp`;

DROP VIEW IF EXISTS `listadoTransacciones`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `listadoTransacciones` AS select `t`.`fecha_mod` AS `fecha_mod`,`c`.`nombre` AS `comercio`,date_format(from_unixtime(`t`.`fecha_mod`),_utf8'%d/%m/%y %H:%i') AS `fecha`,`t`.`idtransaccion` AS `idtransaccion`,(`t`.`valor` / 100) AS `valor`,`t`.`moneda` AS `moneda`,`t`.`estado` AS `estado`,format(((`t`.`valor` / 100) / `t`.`tasa`),2) AS `euros` from (`tbl_transacciones` `t` join `tbl_comercio` `c`) where (`t`.`idcomercio` = `c`.`idcomercio`) order by `t`.`fecha_mod` desc;

DROP VIEW IF EXISTS `mobile_transacciones`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `mobile_transacciones` AS select `t`.`idtransaccion` AS `idtransaccion`,`c`.`nombre` AS `comercio`,`t`.`identificador` AS `identificador`,date_format(from_unixtime(`t`.`fecha_mod`),_utf8'%d/%m/%Y %H:%i') AS `fechaFin`,`m`.`moneda` AS `moneda`,`t`.`fecha_mod` AS `fecha_mod`,round((`t`.`valor_inicial` / 100),2) AS `valorIni`,date_format(from_unixtime(`t`.`fecha`),_utf8'%d/%m/%Y %H:%i') AS `fechaIni`,`t`.`codigo` AS `codigo`,`t`.`fecha` AS `fecha`,`t`.`idcomercio` AS `idcomercio`,`c`.`id` AS `idcom`,round(`t`.`tasa`,4) AS `tasaM`,(case `t`.`estado` when _utf8'B' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * (((`t`.`valor_inicial` - `t`.`valor`) / 100) / `t`.`tasaDev`)),2),round(((`t`.`valor` / 100) / `t`.`tasa`),2)) when _utf8'V' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * (((`t`.`valor_inicial` - `t`.`valor`) / 100) / `t`.`tasaDev`)),2),round(((`t`.`valor` / 100) / `t`.`tasa`),2)) when _utf8'A' then round(((`t`.`valor` / 100) / `t`.`tasa`),2) else _utf8'0.00' end) AS `euroEquiv`,(case `t`.`estado` when _utf8'B' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * ((`t`.`valor_inicial` - `t`.`valor`) / 100)),2),round((`t`.`valor` / 100),2)) when _utf8'V' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * ((`t`.`valor_inicial` - `t`.`valor`) / 100)),2),round((`t`.`valor` / 100),2)) when _utf8'A' then round((`t`.`valor` / 100),2) else _utf8'0.00' end) AS `valorFin`,(case `t`.`estado` when _utf8'P' then _utf8'En Proceso' when _utf8'A' then _utf8'Aceptada' when _utf8'D' then _utf8'Denegada' when _utf8'N' then _utf8'No Procesada' when _utf8'B' then _utf8'Anulada' else _utf8'Devuelta' end) AS `estadoTr`,(case `t`.`tipoEntorno` when _utf8'P' then _utf8'Producci&oacute;n' else _utf8'Desarrollo' end) AS `tipoEntorno`,(case `t`.`estado` when _utf8'P' then _utf8'cssPen' when _utf8'A' then _utf8'cssAce' when _utf8'D' then _utf8'cssDen' when _utf8'N' then _utf8'cssNop' when _utf8'B' then _utf8'cssCan' else _utf8'CssDev' end) AS `classe`,(case `t`.`id_error` when NULL then _utf8'-' when _utf8'' then _utf8'-' else `t`.`id_error` end) AS `error`,(case `t`.`pasarela` when _utf8'0' then NULL else (select `p`.`nombre` AS `nombre` from `tbl_pasarela` `p` where ((`p`.`idPasarela` = `t`.`pasarela`) and (`p`.`idPasarela` = `t`.`pasarela`))) end) AS `pasarl`,(case `t`.`ip` when _utf8'127.0.0.1' then _utf8'no record' else `t`.`ip` end) AS `ip`,(case `t`.`pago` when 0 then _utf8'No' else _utf8'Si' end) AS `tipoPag` from (((`tbl_transacciones` `t` join `tbl_comercio` `c`) join `tbl_pasarela` `p`) join `tbl_moneda` `m`) where ((`t`.`idcomercio` = `c`.`idcomercio`) and (`t`.`pasarela` = `p`.`idPasarela`) and (`t`.`moneda` = `m`.`idmoneda`)) order by `t`.`fecha_mod` desc;

DROP VIEW IF EXISTS `mobile_users`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `mobile_users` AS select `a`.`nombre` AS `nombre`,`a`.`email` AS `email`,`a`.`login` AS `login`,date_format(from_unixtime(`a`.`fecha`),_utf8'%d/%m/%Y') AS `fechaA`,date_format(from_unixtime(`a`.`fecha_visita`),_utf8'%d/%m/%Y %H:%i') AS `fechaV`,replace(`a`.`param`,_utf8'idioma=',_utf8'') AS `idiom`,`a`.`idrol` AS `idrol`,`r`.`nombre` AS `rol`,`a`.`idadmin` AS `idadmin`,(case when ((select count(0) AS `count(*)` from (`tbl_colAdminComer` `c` join `tbl_comercio` `o`) where ((`c`.`idAdmin` = `a`.`idadmin`) and (`c`.`idComerc` = `o`.`id`))) = (select count(0) AS `count(*)` from `tbl_comercio`)) then _utf8'todos' when ((select count(0) AS `count(*)` from (`tbl_colAdminComer` `c` join `tbl_comercio` `o`) where ((`c`.`idAdmin` = `a`.`idadmin`) and (`c`.`idComerc` = `o`.`id`))) = 1) then (select `o`.`nombre` AS `nombre` from (`tbl_colAdminComer` `c` join `tbl_comercio` `o`) where ((`c`.`idAdmin` = `a`.`idadmin`) and (`c`.`idComerc` = `o`.`id`))) else _utf8'varios' end) AS `comercio`,`a`.`fecha` AS `fecha`,(select group_concat(`c`.`idComerc` separator ',') AS `group_concat(c.idComerc separator ',')` from `tbl_colAdminComer` `c` where (`a`.`idadmin` = `c`.`idAdmin`)) AS `idcom`,(case `a`.`activo` when _utf8'S' then _utf8'Si' else _utf8'No' end) AS `activo` from (`tbl_admin` `a` join `tbl_roles` `r`) where (`r`.`idrol` = `a`.`idrol`) order by `a`.`fecha` desc;

DROP VIEW IF EXISTS `vw_ipblancas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `vw_ipblancas` AS select `c`.`nombre` AS `comercio`,`a`.`nombre` AS `admin`,`i`.`fecha` AS `fecha`,date_format(from_unixtime(`i`.`fecha`),_utf8'%d/%m/%Y %H:%i') AS `fechaM`,`i`.`ip` AS `ip` from ((`tbl_ipblancas` `i` join `tbl_comercio` `c`) join `tbl_admin` `a`) where ((`i`.`idAdmin` = `a`.`idadmin`) and (`i`.`idComercio` = `c`.`id`));

DROP VIEW IF EXISTS `mobile_clientes`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `mobile_clientes` AS select `r`.`id_reserva` AS `id_reserva`,`r`.`id_transaccion` AS `id_transaccion`,`c`.`nombre` AS `comercio`,`a`.`nombre` AS `administr`,(case `r`.`est_comer` when _utf8'D' then _utf8'Desarrollo' else _utf8'Producción' end) AS `entorno`,`r`.`codigo` AS `identificador`,`p`.`nombre` AS `pasarela`,`r`.`nombre` AS `cliente`,`r`.`email` AS `email`,`r`.`servicio` AS `servicio`,`r`.`valor_inicial` AS `valor_inicial`,`r`.`valor` AS `valor`,`m`.`moneda` AS `moneda`,date_format(from_unixtime(`r`.`fecha`),_utf8'%d/%m/%Y %H:%i') AS `fechaI`,`r`.`bankId` AS `bankId`,date_format(from_unixtime(`r`.`fechaPagada`),_utf8'%d/%m/%Y %H:%i') AS `fechaII`,date_format(from_unixtime(`r`.`fechaCancel`),_utf8'%d/%m/%Y %H:%i') AS `fechaIII`,`r`.`fecha` AS `fecha`,(case `r`.`pMomento` when _utf8'S' then _utf8'Al momento' else _utf8'Diferido' end) AS `pMom`,(case `r`.`estado` when _utf8'P' then _utf8'En Proceso' when _utf8'A' then _utf8'Aceptada' when _utf8'D' then _utf8'Denegada' when _utf8'N' then _utf8'No Procesada' when _utf8'B' then _utf8'Anulada' else _utf8'Devuelta' end) AS `estadoTr`,(case `r`.`estado` when _utf8'P' then _utf8'cssPen' when _utf8'A' then _utf8'cssAce' when _utf8'D' then _utf8'cssDen' when _utf8'N' then _utf8'cssNop' when _utf8'B' then _utf8'cssCan' else _utf8'CssDev' end) AS `classe`,`r`.`tiempoV` AS `tiempoV`,`r`.`id_comercio` AS `id_comercio`,`c`.`id` AS `idcom` from ((((`tbl_reserva` `r` join `tbl_comercio` `c`) join `tbl_admin` `a`) join `tbl_pasarela` `p`) join `tbl_moneda` `m`) where ((`r`.`id_comercio` = `c`.`idcomercio`) and (`r`.`id_admin` = `a`.`idadmin`) and (`r`.`pasarela` = `p`.`idPasarela`) and (`r`.`moneda` = `m`.`idmoneda`)) order by `r`.`fecha`;

DROP VIEW IF EXISTS `mobile_tickets`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `mobile_tickets` AS select `a`.`nombre` AS `usuario`,`a`.`email` AS `email`,`t`.`fechaModificada` AS `fechaModificada`,date_format(from_unixtime(`t`.`fechaModificada`),_utf8'%d/%m/%Y %H:%i') AS `fecha`,`t`.`asunto` AS `asunto`,(case `t`.`estado` when _utf8'T' then _utf8'Terminado' else _utf8'Activo' end) AS `estadoP`,`t`.`texto` AS `texto`,`a`.`idrol` AS `idrol`,`t`.`idticket` AS `idticket`,`t`.`idadmin` AS `idadmin` from (`tbl_ticket` `t` join `tbl_admin` `a`) where (`t`.`idadmin` = `a`.`idadmin`) order by `t`.`estado`,`t`.`fechaModificada` desc;

DROP VIEW IF EXISTS `vw_transacciones`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `vw_transacciones` AS select `t`.`idtransaccion` AS `id`,`c`.`nombre` AS `comercio`,round(`t`.`tasa`,4) AS `tasaM`,`t`.`estado` AS `estado`,`t`.`fecha` AS `fecha`,`t`.`fecha_mod` AS `fecha_mod`,round((`t`.`valor_inicial` / 100),2) AS `valIni`,`c`.`idcomercio` AS `idcomercio`,`t`.`pasarela` AS `pasarela`,`t`.`tipoEntorno` AS `tipoE`,`t`.`moneda` AS `idmoneda`,`t`.`codigo` AS `codigo`,`t`.`id_error` AS `error`,round(`t`.`tasaDev`,4) AS `tasaDev`,`p`.`nombre` AS `pasarelaN`,`m`.`moneda` AS `moneda`,(case `t`.`estado` when _utf8'B' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * (((`t`.`valor_inicial` - `t`.`valor`) / 100) / `t`.`tasaDev`)),2),round(((`t`.`valor` / 100) / `t`.`tasa`),2)) when _utf8'V' then if((`t`.`fecha_mod` < `t`.`fechaPagada`),round((-(1) * (((`t`.`valor_inicial` - `t`.`valor`) / 100) / `t`.`tasaDev`)),2),round(((`t`.`valor` / 100) / `t`.`tasa`),2)) when _utf8'A' then round(((`t`.`valor` / 100) / `t`.`tasa`),2) else _utf8'0.00' end) AS `euroEquiv`,(case (select count(0) AS `count(*)` from `tbl_reserva` `r` where (`r`.`codigo` = `t`.`identificador`)) when 1 then concat(_utf8'<a href="index.php?componente=comercio&pag=cliente&val=',`t`.`identificador`,_utf8'">',`t`.`identificador`,_utf8'</a>') else `t`.`identificador` end) AS `identificador`,(case `t`.`estado` when _utf8'P' then _utf8'green' when _utf8'A' then _utf8'black' when _utf8'D' then _utf8'red' when _utf8'N' then _utf8'red' when _utf8'B' then _utf8'blue' else _utf8'blue' end) AS `color{col}`,(case `t`.`ip` when _utf8'127.0.0.1' then _utf8'no record' else `t`.`ip` end) AS `ip`,(case `t`.`ip` when _utf8'127.0.0.1' then _utf8'no record' else `t`.`ip` end) AS `geo{geoip}`,(case `t`.`pago` when 0 then _utf8'No' else _utf8'Si' end) AS `pagada`,(case `t`.`estado` when _utf8'B' then round(if((`t`.`fecha_mod` < `t`.`fechaPagada`),(-(1) * ((`t`.`valor_inicial` - `t`.`valor`) / 100)),(`t`.`valor` / 100)),2) when _utf8'V' then round(if((`t`.`fecha_mod` < `t`.`fechaPagada`),(-(1) * ((`t`.`valor_inicial` - `t`.`valor`) / 100)),(`t`.`valor` / 100)),2) else round((`t`.`valor` / 100),2) end) AS `valor`,(case `t`.`tipoEntorno` when _utf8'P' then _utf8'Producci&oacute;n' else _utf8'Desarrollo' end) AS `tipoEntorno`,(case `t`.`estado` when _utf8'P' then _utf8'En Proceso' when _utf8'A' then _utf8'Aceptada' when _utf8'D' then _utf8'Denegada' when _utf8'N' then _utf8'No Procesada' when _utf8'B' then _utf8'Anulada' else _utf8'Devuelta' end) AS `estad` from (((`tbl_transacciones` `t` join `tbl_comercio` `c`) join `tbl_moneda` `m`) join `tbl_pasarela` `p`) where ((`c`.`idcomercio` = `t`.`idcomercio`) and (`t`.`moneda` = `m`.`idmoneda`) and (`p`.`idPasarela` = `t`.`pasarela`));

drop trigger tr_inscomer;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` TRIGGER `tr_inscomer` AFTER INSERT ON `tbl_comercio` FOR EACH ROW begin
	declare idAdm int;
	declare no_more_rows boolean;
	declare idCom int default new.id;
	declare num_rows int default 0;
	
	declare cur_usuarios cursor for select a.idadmin from tbl_admin a where idrol < 11;
	declare continue handler for not found set no_more_rows = true;
	
	open cur_usuarios;
		select FOUND_ROWS() into num_rows;
			el_lazo: loop
				fetch cur_usuarios into idAdm;
				if no_more_rows then
					close cur_usuarios;
					leave el_lazo;
				end if;
				insert into tbl_colAdminComer (idComerc,idAdmin) values (idCom,idAdm);
			end loop el_lazo;
end;;

drop trigger tr_uptcomer;
CREATE DEFINER=`root`@`localhost` TRIGGER `tr_uptcomer` BEFORE UPDATE ON `tbl_comercio` FOR EACH ROW begin
	if (new.activo != old.activo) then call estadComer(old.id, new.activo); end if;
end;;

DELIMITER ;